spring:
  datasource:
    username: root
    password: tang1212
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  jpa:
    show-sql: true
  activiti:
    check-process-definitions: false
mybatis:
  mapper-locations: mapping/*.xml
server:
  port: 8081
  servlet:
    context-path: /activity
    session:
      timeout: 10
  tomcat:
    uri-encoding: UTF-8

#spring.jpa.properties.hibernate.hbm2ddl.auto=update
#spring.jpa.show-sql=true
#server.port=8081
#server.context-path=/activity
#server.session.timeout=10
#server.tomcat.uri-encoding=UTF-8